README.md

There was a typo in one of the titles, and both spellings of 'customize'. Have also added in spaces before the markdown header definitions, which makes the readme easier to read (when editing).

Typo fix, and standardizing header spacing

---

lib/raygun.rb
lib/raygun/client.rb
raygun4ruby.gemspec
test/unit/client_test.rb

Adds a stderr message rather than raising when API Key config is missing
(Fixes #62)

Don't raise when API Key Is missing

---

lib/raygun/client.rb
test/unit/client_test.rb

Tags are currently hardcoded against the RACK_ENV variable. This change allows you to pass in adhoc tags, alongside the custom_data, in the form of an array. 
It maintains backwards compatibility with the existing functionality by merging in the rack_env var to the tag array. 
The rack env access properties were also renamed for clarity.

Allow tags to be set

---

lib/raygun/client.rb
lib/raygun/configuration.rb
test/unit/client_test.rb
test/unit/configuration_test.rb

Resolves issue #72.
Adds a `tags` config option which allows users to set an array of tags which will be passed with every exception sent to the API. 
Example usage:
```ruby
Raygun.setup do |config|
config.tags = ['heroku']
end
```

Allow tags to be set in configuration

---

.travis.yml
lib/raygun/railtie.rb

When running a Rails 5.0.0.beta4 web app with the lastest version of Raygun4ruby, I get this:
```bash
DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
them to actual class references.  For example:
"ActionDispatch::DebugExceptions" => ActionDispatch::DebugExceptions
(called from get_class at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta4/lib/action_dispatch/middleware/stack.rb:116)
DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
them to actual class references.  For example:
"Raygun::Middleware::RackExceptionInterceptor" => Raygun::Middleware::RackExceptionInterceptor
(called from get_class at …
```

Remove deprecation warnings when using Rails 5

---

README.md

-show the default ignored exception types in the wiki
-update source code link (to ignored exception types) to correct line number

Show Default Ignored Exception Types on Doc page

---

lib/raygun/client.rb

Currently `custom_data` is not filtered when it is sent from the provider.  
This pull request modifies portions of the `lib/raygun/client.rb` to apply the same filtering process used for `raw_data` to `custom_data` via a new method:  `filter_custom_data`.  This new method utilizes the same logic as `form_params` and handles the `custom_data = env.delete(:custom_data) that `build_payload_hash` had implemented previously.
A small change was also made to `filter_params_with_array` to ensure that all values would be compared as strings, as opposed to symbols which `custom_data` was passing in.
Further backstory and reasoning sent via email to Nik.

Allow Filtering of Custom_Data

---

lib/raygun/client.rb
test/unit/client_test.rb

This change ensures that parameters such as `password_confirmation` are
not sent to the server.
Previously parameters were only filtered when their name exactly matched
a member of the `filter_parameters` list. The test
`test_filter_parameters_using_proc` in `client_test.rb` uses a custom
`Proc` to demonstrate filtering of all parameters starting with
'nsa_only'. This is a valid demonstration however the default
configuration for Rails applications uses a different code path not
containing the logic from that `Proc`.
A default configuration for Rails applications is something like the
following where the Raygun client inherits the filter list from Rails as
an array of Symbols. In most cases this will result in an Array
containing a single element `:password`.
```
config.filter_parameters …
```

Prevent logging of password confirmations

---

lib/raygun/client.rb

Rails env should be preferred over rack env if present. We have several applications with the same rack env but with a specific Rails env so the gem is adding the wrong environment tag (rack env instead of rails env).

In tags, insert rails_env instead of rack_env if present

---

.travis.yml
raygun4ruby.gemspec

httparty 0.13.7 requires json 1.8, and json 1.8 not working with ruby 2.4

Allow to use httparty 0.14.0

---

CHANGELOG.md
README.md
lib/raygun.rb
lib/raygun/client.rb
lib/raygun/configuration.rb
lib/raygun/services/apply_whitelist_filter_to_payload.rb
lib/raygun/version.rb
raygun4ruby.gemspec
specs/services/apply_whitelist_filter_to_payload_spec.rb
test/unit/client_test.rb
test/unit/configuration_test.rb

By request, a new config option `filter_payload_with_whitelist` (set to false by default) which reuses `filter_parameters`, but changes it to sanitize all values if they are not present in that array. This is applied recursively and for all nodes in the payload, e.g both branch and leaf nodes, barring the required occurredOn, details and client hashes.
Also includes a fix when running tests locally without a Rails gem installed (rails_env gets a `nil` tag appended).

Add option to filter entire payload using whitelist approach

---

CHANGELOG.md
lib/raygun.rb

Try a single time to send an exception generated when track_exception is
called to raygun with the original exceptions backtrace attached as
custom data
Resolves #99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/104)

Notify raygun when raygun4ruby raises an exception

---

CHANGELOG.md
lib/raygun/services/apply_whitelist_filter_to_payload.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/105)

dup hashes before applying whitelist filter to them

---

CHANGELOG.md
README.md
lib/raygun.rb
lib/raygun/affected_user.rb
lib/raygun/configuration.rb
lib/raygun/middleware/rails_insert_affected_user.rb
test/unit/affected_user_test.rb

Initial work on upgrading affected user tracking.
Ping @MindscapeHQ/ruby-team, @armstrjare, @NZKoz, @CmdrKeen for feedback :)

Upgrade Affected User Tracking

---

lib/raygun.rb
lib/raygun/client.rb
lib/raygun/error.rb
test/unit/client_test.rb

To support the case:
I want to raise an exception and have my Rack middleware(s) handle it. However, I also want to include custom data to raygun.
AFAICT this case was not supported, so here we are. Open to feedback. Thanks!

Introduce exception raygun_custom_data instance method

---

CHANGELOG.md
lib/raygun/client.rb
lib/raygun/configuration.rb
lib/raygun/version.rb
test/unit/configuration_test.rb

Make api url configurable via `Configuration.api_url`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/111)

Configurable api url

---

CHANGELOG.md
lib/raygun.rb
lib/raygun/client.rb
lib/raygun/configuration.rb
lib/raygun/version.rb
test/unit/client_test.rb
test/unit/configuration_test.rb

The body of a POST request was not being correctly recorded by the raw_data method before. This makes it so Raygun will correctly read the body of POST requests out of the request when an exception occurs and send it along with the payload. Because this does not go through the blacklisting process (due to the fact it's arbitrary string data) form submissions are not included in this. The request gets truncated to 4096 characters.
Because sensitive data may be in the request body this is opt in behind a configuration flag.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/116)

Correctly record raw request data for Rack based apps

---

CHANGELOG.md
README.md
lib/raygun.rb
lib/raygun/client.rb
lib/raygun/configuration.rb
lib/raygun/version.rb
raygun4ruby.gemspec
test/unit/client_test.rb
test/unit/configuration_test.rb

Send exceptions in background thread via concurrent-ruby
Disabled by default, can be enabled with config flag `send_in_background` set to true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/117)

Background sending of exceptions so web request thread is not blocked

---

lib/raygun/client.rb
test/unit/client_test.rb

This changes the raw_data method to only use methods allowed on the
input buffer by the rack specification. This fixes raw_data for unicorn.
Raw data handling tested in Phusion Passenger (v5), Unicorn (v5) and
Puma (v3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/125)

Make raw_data handling more robust and fix in unicorn

---

lib/raygun/configuration.rb

fix: raygun ruby undefined method `Identifier` for nil:NilClass

Backward compatible affected_user_identifier_methods

---

CHANGELOG.md
Rakefile
lib/raygun.rb
lib/raygun/client.rb
lib/raygun/configuration.rb
lib/raygun/version.rb
raygun4ruby.gemspec
specs/raygun/raygun_spec.rb
specs/spec_helper.rb
test/test_helper.rb
test/unit/client_test.rb
test/unit/configuration_test.rb
test/unit/resque_failure_test.rb
test/unit/sidekiq_failure_test.rb

Adds configuration option for setting the timeout of the POST call to the API server when submitting a crash report.
This is primarily to ensure that when using the send_in_background configuration option that network issues don't cause a bunch of observables to stick around waiting for the network call to finish clogging up memory and threads.
Also bumps rake from v0.9.6 to v11 and replaces Fakeweb with webmock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/129)

Timeout network request to send crash reports to API

---

CHANGELOG.md
lib/raygun/middleware/javascript_exception_tracking.rb
lib/raygun/version.rb

This fixes #139 by not touching the response object if no JS api key is present and not attempting to modify the response if it does not respond to `[]`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/140)

Fixes #139

---

lib/raygun/middleware/javascript_exception_tracking.rb

- Getting error  ```*** NoMethodError Exception: undefined method `include?' for nil:NilClass```
for this block in `JavascriptExceptionTracking` class
```ruby
if headers['Content-Type'].include?('text/html')
response = inject_javascript_to_response(response)
end
```
- somehow the `headers['Content-Type']` is nil when there's 404 exception and getting 500 error instead of 404
- Using `Rails 5.1.6` and `jbuilder` gem with json format response

Safe calling content-type header for Javascript exception tracking

---

lib/raygun.rb
lib/raygun/breadcrumbs/breadcrumb.rb
lib/raygun/breadcrumbs/store.rb
lib/raygun/client.rb
raygun4ruby.gemspec
spec/raygun/breadcrumbs/breadcrumb_spec.rb
spec/raygun/breadcrumbs/store_spec.rb

When sending an exception causes an exception, clear the breadcrumbs store before trying to send the failure exception. This is partially because sending a giant exception payload causes an exception which could be caused by breadcrumbs (this is mitigated with the second change however) and because something in the breadcrumbs could be causing the problem.
The primary mitigation to the error that occurs during sending a very large payload is to only send the most recent breadcrumbs up to a size limit of 100KB which should address this problem without having to lose all the breadcrumbs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4ruby/147)

Improve failsafe exception retrying & large breadcrumb support

---

.travis.yml
raygun4ruby.gemspec
spec/dummy/app/assets/config/manifest.js
test/test_helper.rb

- Update rake to the version recommended by dependabot
- Fix path to `mocha/minitest`
- Implement fix specified [here](https://docs.travis-ci.com/user/languages/ruby/#bundler-20) around supporting older versions of Ruby
- Specify use of `rspec-rails` to v3 (which still supports Ruby < v2.3)
- Update manifest.js for the dummy app (which was a requirement)

Update project dependencies

---

README.md
lib/raygun/client.rb
lib/raygun/configuration.rb
lib/raygun/testable.rb
raygun4ruby.gemspec
test/test_helper.rb
test/unit/configuration_test.rb
test/unit/resque_failure_test.rb
test/unit/sidekiq_failure_test.rb

- Change instances of raygun.io to raygun.com
- Update old links to point at the docs
- Update API base URL from `api.raygun.io` to `api.raygun.com`

Update instances of raygun.io to raygun.com, update old links

---

CHANGELOG.md
lib/raygun/sidekiq.rb
lib/raygun/version.rb

This change will cause errors originating from sidekiq code to be tagged with `sidekiq` in Crash Reporting in the Raygun app.
Closes #159

Set sidekiq tag on sidekiq errors

---

CHANGELOG.md
lib/raygun.rb
lib/raygun/demo_exception.rb
lib/raygun/raygun_testable.rb
lib/raygun/version.rb

In Ruby 2.7.2, the built gem does not include the `lib/raygun/testable.rb` file due to the regex in the gemspec [here](https://github.com/MindscapeHQ/raygun4ruby/blob/master/raygun4ruby.gemspec#L17). This has been renamed so that it no longer contains "test" in the file name.

Rename Testable class

---

lib/raygun.rb

Hi, I wrote something like this into our raygun wrapper module in our application code and thought might as well see if you think more of your users would enjoy this feature.
Instantiated and Tracked vs Instantiated, Raised, Rescued, and Tracked
This error has `backtrace` of `nil`:
```ruby
error = StandardError.new("I'm an error")
track_exception(error) unless some_condition?
```
vs
This error has a complete `backtrace`:
```ruby
begin
raise StandardError.new("I'm an error") unless some_condition?
rescue StandardError => error
track_exception(error)
end
```
- This PR makes it so if the `error` does not have a `backtrace` already, `track_exception` will call `set_backtrace` and pass in the current callstack using [Ruby `Kernel`'s `caller` method thanks to this StackOverflow …

Use Kernel.caller if exception has nil backtrace

---

lib/raygun/configuration.rb

`Sidekiq::JobRetry::Skip` is used for retry control and isn't really a resolvable error to track
As per [recommendation from the Sidekiq maintainer](https://github.com/rails/rails/pull/43625#issuecomment-1071632022)

Adds internal Sidekiq class to default ignore list

---

README.md
lib/raygun/demo_exception.rb

Split usage into steps, and clarify Raygun dashboard -> Crash Reporting dashboard

Minor README tweaks

---

lib/raygun/sidekiq.rb
test/unit/sidekiq_failure_test.rb

We are expecting a `config` argument to the Sidekiq exception handler, but pre- version 7.1.5 that is not passed.
So we'll make the argument optional as it is currently unnused anyway
Fixes #183

Fixes backward incompatible Sidekiq change

---

README.md
lib/raygun/configuration.rb
lib/raygun/error_subscriber.rb
lib/raygun/sidekiq.rb
test/unit/sidekiq_failure_test.rb

This means the inner exception is reported to Raygun, with a tag `sidekiq_retry` of "true".
Also adds a config setting to disable this behaviour and reporting of retried Sidekiq jobs (`config.track_retried_sidekiq_jobs` defaults to true)

Unwraps `Sidekiq::JobRetry::Handled` errors

---

raygun4ruby.gemspec

Ruby 3.3.5 emits a warning that `ostruct` will be removed from stdlib default gems in Ruby 3.5
```
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/raygun4ruby-x.x.x/lib/raygun.rb:7: warning:
/.rbenv/versions/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
```

Add ostruct runtime dependency to fix warning in ruby 3.3.5+

---

lib/raygun.rb
lib/raygun/configuration.rb
test/unit/raygun_test.rb
test/unit/sidekiq_failure_test.rb

Adds two new configuration settings:
* Configure how many times raygun4ruby should retry sending the error to the Raygun servers using `error_report_max_attempts` (defaults to 1)
* Configure whether or not raygun4ruby should re-raise an exception if the send fails using `raise_on_failed_error_report` (defaults to false)

Adds support for a retry count and raising
